// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDWMBho4fXKCi6E79VbFw_oZkNXqZIoI',
    appId: '1:161041119415:android:b0a62aa39814b922377532',
    messagingSenderId: '161041119415',
    projectId: 'gardenguard-62af1',
    databaseURL: 'https://gardenguard-62af1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gardenguard-62af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkeApRDugGOWo6J5JascVGXuCP9UUPKwk',
    appId: '1:161041119415:ios:9616f9a9fbc1c83d377532',
    messagingSenderId: '161041119415',
    projectId: 'gardenguard-62af1',
    databaseURL: 'https://gardenguard-62af1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gardenguard-62af1.appspot.com',
    iosClientId: '161041119415-oke4atp7jdovdiou6k3760g9k22l4il0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenGuard',
  );
}
